controller_manager:
  ros__parameters:
    update_rate: 1000 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    tsid_controller:
      type: tsid_controller/TsidController

    torque_controller:
      type: effort_controllers/JointGroupEffortController

    motion_control_handle:
      type: cartesian_controller_handles/MotionControlHandle


tsid_controller:
  ros__parameters:
    controlled_joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6

    end_effector:  # Cartesian end-effector task
      weight: 10.0
      # controlled_frame: "jointGripper"
      # controlled_frame: "gripperStatorLink"
      controlled_frame: "link06"
      kp: 
        - 5000.0
        - 5000.0
        - 5000.0
        - 5000.0
        - 5000.0
        - 3000.0
#     kd: 
#       - 5000.0
#       - 5000.0
#       - 5000.0
#       - 5000.0
#       - 5000.0
#       - 3000.0

    posture:  # Postural task
      weight: 1.0
      k: 10.0
      desired_configuration:
        - 1.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0

    use_torque_limits: true
    torque_limits:
      - 25.0
      - 25.0
      - 20.0
      - 10.0
      - 10.0
      - 10.0

    use_joint_limits: true
    joint_limit_dt: 0.3


torque_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6

motion_control_handle:
  ros__parameters:
    end_effector_link: "wrist_3_link"
    robot_base_link: "base_link"
    ft_sensor_ref_link: "wrist_3_link"
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
